BLOCK_DATA_TYPES = {
    1: "TriangleGeometry",
    11: "PrimitiveGeometry",
    21: "Scene",
    22: "Container",
    23: "MeshInstance",
    31: "SkyBox",
    41: "Light",
    42: "Camera",
    43: "TextureProjector",
    51: "LightPicker",
    81: "StandardMaterial",
    82: "Texture",
    83: "CubeTexture",
    91: "SharedMethod",
    92: "ShadowMethod",
    101: "Skeleton",
    102: "SkeletonPose",
    103: "SkeletonAnimation",
    111: "MeshPose",
    112: "MeshPoseAnimation",
    113: "AnimationSet",
    121: "UVAnimation",
    122: "Animator",
    253: "Command",
    254: "Namespace",
    255: "Meta-data"
}
